import { Flex } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SideBar from "./_components/SideBar";
import { ChakraUIProvider } from "./_components/ui/ChrakraUIProvider";
import MSWProvider from "./_components/ui/MSWProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Products Catalogue Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <MSWProvider>
          <ChakraUIProvider>
            <Flex>
              <SideBar />
              <Flex direction="column" pt={4} w="full" mx="auto" maxW="1200px">
                {children}
              </Flex>
            </Flex>
          </ChakraUIProvider>
        </MSWProvider>
      </body>
    </html>
  );
}
