import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "./_components/ui/provider";

import "./globals.css";
import { Box, Flex } from "@chakra-ui/react";
import SideBar from "./_components/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Provider>
          <Flex>
            <SideBar />
            <Box pt={4} px={5}>
              {children}
            </Box>
          </Flex>
        </Provider>
      </body>
    </html>
  );
}
